name: Build

on:
  workflow_dispatch:
  schedule:
   - cron:  '0 */6 * * *' # Every 6 hours

jobs:
  latest_release:
    name: 'Latest Release'
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0
      - name: GIT Setup
        run: |
          git config --global user.name '@Salakar'
          git config --global user.email 'Salakar@users.noreply.github.com'
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set Github Token Securely
        run: echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - name: Process Latest Version
        run: |
          ./.github/workflows/scripts/process-latest-version.sh
      - name: Report Failure Status
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.INVERTASEBOT_SLACK_GITHUB_CHANNEL_WEBHOOK_URL }}
          SLACK_COLOR: '#FF0000'
          SLACK_USERNAME: 'InvertaseBot'
          SLACK_TITLE: ':bell: Build Failure'
          SLACK_ICON: 'https://static.invertase.io/assets/invertase-logo-small.png'
          SLACK_MESSAGE: 'An invertase/firestore-ios-sdk-frameworks build has failed!'
          SLACK_FOOTER: 'https://github.com/invertase/firestore-ios-sdk-frameworks/actions'
