name: Build

on:
  workflow_dispatch:
  schedule:
   - cron:  '0 */6 * * *' # Every 6 hours

jobs:
  latest_release:
    name: 'Latest Release'
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0
      - name: GIT Setup
        run: |
          git config --global user.name '@Salakar'
          git config --global user.email 'Salakar@users.noreply.github.com'
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set Github Token Securely
        run: echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - name: Process Latest Version
        run: |
          ./.github/workflows/scripts/process-latest-version.sh
      - name: Report Failure Status
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,repo
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} of ${process.env.AS_REPO} on firebase-ios-sdk ${process.env.LATEST_FIREBASE_VERSION} ${{ job.status }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.INVERTASEBOT_SLACK_GITHUB_CHANNEL_WEBHOOK_URL }}
        if: failure()
